# Generated by Django 4.2.11 on 2024-11-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('registration_number', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.AutoField(primary_key=True, serialize=False)),
                ('num_of_rooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('tv', models.BooleanField(default=False)),
                ('fridge', models.BooleanField(default=False)),
                ('num_of_beds', models.IntegerField()),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('semi-lux', 'Semi-lux'), ('lux', 'Lux')], max_length=50)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_code', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('num_of_days', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
    ]
